### ISSUE TITLE
Tabu wird nicht angezeigt

### ISSUE THREAD

**Issue by jannis6023** [Kovah/Taboo#16]
Hallo, auf einem Apache-Server entpackt funktioniert leider nicht die taboo-build.zip. Es wird mir eine leere, weiße Seite angezeigt. Leider wird auch nirgends ein JS-Script o.ä. geladen. Kann mir da jemand helfen?

**Comment by Kovah** [comment]
Das Spiel scheint bei mir richtig zu laufen. Könntest du die Apache Konfiguration teilen? Gerne Domains durch Platzhalter ersetzen.

Das HTML in der index.html Datei sollte so in der Art aussehen:
```html
<!DOCTYPE html><html lang=de><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1"><link rel=apple-touch-icon sizes=180x180 href=/apple-touch-icon.png> [....] <meta property=og:description content="A Taboo-based game for your browser by Kovah.de"><link as=style href=css/app.258072b8.css rel=preload><link as=script href=js/app.7edbc52c.js rel=preload><link as=script href=js/chunk-vendors.91a5eacc.js rel=preload><link href=/css/app.258072b8.css rel=stylesheet></head><body><noscript><strong>We're sorry but Taboo doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id=app></div><script src=js/chunk-vendors.91a5eacc.js></script><script src=js/app.7edbc52c.js></script></body></html>
```

**Comment by jannis2200** [comment]
Ok, welche Config genau? Bei mir in der HTML fehlt beispielsweise der gesamte Teil mit JS und CSS.

**Comment by jannis2200** [comment]
Im DIV mit der id App steht BTW auch nix drinnen

**Comment by Kovah** [comment]
Hast du auch die https://github.com/Kovah/Taboo/releases/download/v2.1.1/taboo-build_2.1.1.zip Datei herunter geladen? Habe gerade gesehen, dass die neuste Version (2.1.2) keine fertigen Dateien beinhaltet.

**Comment by jannis2200** [comment]
![image](https://user-images.githubusercontent.com/40733092/91213948-a6acee00-e712-11ea-8844-bc9787be3e47.jpeg)
Die hier habe ich runtergeladen.

**Comment by jannis2200** [comment]
Und in der Index wird der Code auch nicht angezeigt.
![image](https://user-images.githubusercontent.com/40733092/91214602-99443380-e713-11ea-9b95-f86d7112f806.jpeg)

**Comment by Kovah** [comment]
Okay das ist mega strange. Ich werde morgen noch mal eine neue Version bauen. Vielleicht ist was mit dem Paket nicht in Ordnung,

**Comment by Kovah** [comment]
Bitte mal hiermit testen: https://github.com/Kovah/Taboo/releases/download/v2.1.2/Taboo_2.1.2.zip

**Comment by Kovah** [comment]
Hi, hast du noch Feedback zu diesem Thema?

**Comment by Kovah** [comment]
Wenn es noch mal Feedback gibt gerne das Ticket erneut öffnen.
