### ISSUE TITLE
Absoulte Pfade im HTML

### ISSUE THREAD

**Issue by Ottokranz** [Kovah/Taboo#19]
Ich habe das Spiel in einen Unterordner auf meinem Webserver kopiert und bekam nur eine weiße Seite. Im HTML sind absolute Pfade auf das Root Verzeichnis angegeben (/js/xyz.js) Wenn man das erste Slash in den Pfaden entfernt, funktioniert das Spiel auch in einem Unterordner.

**Comment by Kovah** [comment]
Hi. Ich habe jetzt mit der neuen Version 3 eine neue Variante erstellt, die komplett relative Pfade nutzt. Die kann im Release heruntergeladen werden: https://github.com/Kovah/Taboo/releases/tag/v3.0.0
